version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: ucu_salas_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: manuelmanuel
      MYSQL_DATABASE: ucu_salas
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql